### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by lwgpshit** [simon300000/bilibili-live-ws#78]
Connection is established
(node:12659) UnhandledPromiseRejectionWarning: TypeError: packs.flatMap is not a function
    at Object.exports.decoder (/home/apple/danmuku/node_modules/_bilibili-live-ws@5.1.0@bilibili-live-ws/src/buffer.js:45:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12659) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12659) UnhandledPromiseRejectionWarning: TypeError: packs.flatMap is not a function
    at Object.exports.decoder (/home/apple/danmuku/node_modules/_bilibili-live-ws@5.1.0@bilibili-live-ws/src/buffer.js:45:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12659) UnhandledPromiseRejectionWarning: TypeError: packs.flatMap is not a function
    at Object.exports.decoder (/home/apple/danmuku/node_modules/_bilibili-live-ws@5.1.0@bilibili-live-ws/src/buffer.js:45:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:12659) UnhandledPromiseRejectionWarning: TypeError: packs.flatMap is not a function
    at Object.exports.decoder (/home/apple/danmuku/node_modules/_bilibili-live-ws@5.1.0@bilibili-live-ws/src/buffer.js:45:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:12659) UnhandledPromiseRejectionWarning: TypeError: packs.flatMap is not a function
    at Object.exports.decoder (/home/apple/danmuku/node_modules/_bilibili-live-ws@5.1.0@bilibili-live-ws/src/buffer.js:45:18)

**Comment by simon300000** [comment]
应该是nodejs版本太低了，加一个Array.flatMap支持试试？

**Comment by lwgpshit** [comment]
感谢，请问这怎么回事
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at Socket.Writable.write (_stream_writable.js:292:11)
    at LiveTCP.send (/home/apple/danmaku/node_modules/_bilibili-live-ws@5.1.0@bilibili-live-ws/src/index.js:130:20)
    at LiveTCP.heartbeat (/home/apple/danmaku/node_modules/_bilibili-live-ws@5.1.0@bilibili-live-ws/src/index.js:101:14)
    at Timeout._onTimeout (/home/apple/danmaku/node_modules/_bilibili-live-ws@5.1.0@bilibili-live-ws/src/index.js:67:58)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Emitted 'error' event on LiveTCP instance at:
    at LiveTCP.emit (/home/apple/danmaku/node_modules/_bilibili-live-ws@5.1.0@bilibili-live-ws/src/index.js:34:15)
    at LiveTCP.<anonymous> (/home/apple/danmaku/node_modules/_bilibili-live-ws@5.1.0@bilibili-live-ws/src/index.js:97:18)
    at LiveTCP.emit (events.js:315:20)
    at LiveTCP.emit (/home/apple/danmaku/node_modules/_bilibili-live-ws@5.1.0@bilibili-live-ws/src/index.js:34:15)
    at Socket.<anonymous> (/home/apple/danmaku/node_modules/_bilibili-live-ws@5.1.0@bilibili-live-ws/src/index.js:137:48)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'

**Comment by simon300000** [comment]
这个好像是我这边的问题，你用的是KeepLiveTCP还是LiveTCP？

**Comment by lwgpshit** [comment]
用的LiveTCP

**Comment by simon300000** [comment]
看起来是TCP连接断了但是还在发东西 是我这里的问题 hiehie

**Comment by lwgpshit** [comment]
感谢，但是我是乱写的

**Comment by simon300000** [comment]
啊，send是你写的吗？这个好像是TCP连接已经关闭了但是还要发东西出去导致的问题

**Comment by lwgpshit** [comment]
没写我也不知道

**Comment by simon300000** [comment]
那我也不知道啦
